return {
	-- "rebelot/kanagawa.nvim",
	-- name = "kanagawa",
	--
	-- opts = {
	-- 	compile = true, -- enable compiling the colorscheme
	-- 	undercurl = true, -- enable undercurls
	-- 	commentStyle = { italic = true },
	-- 	functionStyle = {},
	-- 	keywordStyle = { italic = true },
	-- 	statementStyle = { bold = true },
	-- 	typeStyle = {},
	-- 	transparent = false, -- do not set background color
	-- 	dimInactive = false, -- dim inactive window `:h hl-NormalNC`
	-- 	terminalColors = true, -- define vim.g.terminal_color_{0,17}
	-- 	colors = { -- add/modify theme and palette colors
	-- 		palette = {},
	-- 		theme = { wave = {}, lotus = {}, dragon = {}, all = {} },
	-- 	},
	-- 	overrides = function(colors) -- add/modify highlights
	-- 		return {
	--
	-- 			-- ["@include.member.move"] = { fg = "#89b4fa" },
	-- 			-- ["@namespace.module.name.move"] = { fg = "#b4befe" },
	-- 			-- ["@macro.call.move"] = { fg = "#e78284" },
	-- 			-- ["@list.variable.move"] = { fg = colors.palette.fujiWhite },
	-- 			["@include.member.move"] = { fg = colors.palette.crystalBlue },
	-- 			["@constructor.name.move"] = { fg = colors.palette.waveAqua2 },
	-- 			["@namespace.module.name.move"] = { fg = "#b4befe" },
	-- 			["@macro.call.move"] = { fg = colors.palette.autumnRed },
	-- 			["@function.call.move"] = { fg = colors.palette.crystalBlue },
	-- 			["@list.variable.move"] = { fg = "#bac2de" },
	-- 			["@list.move"] = { fg = colors.palette.waveRed },
	-- 		}
	-- 	end,
	-- 	theme = "dragon", -- Load "wave" theme when 'background' option is not set
	-- 	background = { -- map the value of 'background' option to a theme
	-- 		dark = "wave", -- try "dragon" !
	-- 		light = "lotus",
	-- 	},
	-- },
}
