return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "vim",
      "lua",
      "vimdoc",
      "html",
      "http",
      "diff",
      "graphql",
      "css",
      "c",
      "solidity",
      "typescript",
      "tsx",
      "javascript",
      "json",
      "jsonc",
      "jsdoc",
      "rust",
      "markdown_inline",
      "markdown",
      "query",
      "regex",
      "yaml",
      "sql",
      "toml",
      "slint",
      "editorconfig",
      "git_config",
      "git_rebase",
      "gitcommit",
      "gitignore",
      "kconfig",
      "kdl",
      "latex",
      'norg',
      'scss',
      'svelte',
      'typst',
      'vue'
    },
    auto_install = true,
    highlight = {
      enable = true, -- Enable syntax highlighting
      additional_vim_regex_highlighting = false,
    },
  },
}
