return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "vim",
      "lua",
      "vimdoc",
      "html",
      "css",
      "solidity",
      "typescript",
      "tsx",
      "javascript",
      "json",
      "rust",
      "markdown",
      "yaml",
      "slint",
      "editorconfig",
      "git_config",
      "git_rebase",
      "gitcommit",
      "gitignore",
    },
  },
}
