-- vim.lsp.enable({
-- 	"lua_ls",
-- 	"solidity_ls_nomicfoundation",
-- 	"vtsls",
-- })
--
-- vim.diagnostic.config({
-- 	virtual_text = true,
-- 	underline = true,
-- 	update_in_insert = false,
-- 	severity_sort = true,
-- 	float = {
-- 		border = "rounded",
-- 		source = true,
-- 	},
-- 	signs = {
-- 		text = {
-- 			[vim.diagnostic.severity.ERROR] = "",
-- 			[vim.diagnostic.severity.WARN] = "",
-- 			[vim.diagnostic.severity.HINT] = "󰌵",
-- 			[vim.diagnostic.severity.INFO] = "",
-- 		},
-- 		numhl = {
-- 			[vim.diagnostic.severity.ERROR] = "ErrorMsg",
-- 			[vim.diagnostic.severity.WARN] = "WarningMsg",
-- 		},
-- 	},
-- })
